[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_error_codes = ["license", "pragma-solidity", 3420,2018, 2072, 5667,2519, 2462, 3628]

[rpc_endpoints]
ETH2="https://eth.llamarpc.com"
ETH="https://lb.drpc.org/ogrpc?network=ethereum&dkey=Agj3H7SHJkO-iMX1gGfisZ5sR45LXTYR7oTwFnomaLKw"
BSC="https://lb.drpc.org/ogrpc?network=bsc&dkey=Agj3H7SHJkO-iMX1gGfisZ5sR45LXTYR7oTwFnomaLKw"
ARB="https://lb.drpc.org/ogrpc?network=arbitrum&dkey=Agj3H7SHJkO-iMX1gGfisZ5sR45LXTYR7oTwFnomaLKw"
OPT="https://lb.drpc.org/ogrpc?network=optimism&dkey=Agj3H7SHJkO-iMX1gGfisZ5sR45LXTYR7oTwFnomaLKw"
BASE="https://lb.drpc.org/ogrpc?network=base&dkey=Agj3H7SHJkO-iMX1gGfisZ5sR45LXTYR7oTwFnomaLKw"
ARB2="https://arb1.arbitrum.io/rpc"
BASE2="https://1rpc.io/base"
      

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


